name: Build

on: [push]

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        include:
        - os: ubuntu-latest
          package-file: DDNet-Server
          env:
            CFLAGS: -Wdeclaration-after-statement -Werror
            CXXFLAGS: -Werror
        - os: windows-2019
          package-file: DDNet-Server.exe
          env:
            CFLAGS: /WX
            CXXFLAGS: /WX
            LDFLAGS: /WX

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install libsqlite3-dev cmake -y

    - name: Build in release mode
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=./
        cmake --build ./ --config Release

    - name: Move release
      if: contains(matrix.os, 'windows')
      run: mv ./release/${{ matrix.package-file }} ./

    - name: Test release
      run: ./${{ matrix.package-file }} shutdown

    - name: Package
      run: |
        mkdir artifacts
        mv ${{ matrix.package-file }} artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hunter-${{ matrix.os }}-build-cmake
        path: artifacts